const toppersRaw = [
  // 2019-20 (Year 2020)
  { year: "2020", class: "TY", rank: "1", name: "Telore Manoj Pandurang", marks: "-", percentage: "86.03%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "TY", rank: "2", name: "Dipali Gore Babasaheb", marks: "-", percentage: "86.03%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "TY", rank: "3", name: "Surase Tejas Sandip", marks: "-", percentage: "85.33%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "SY", rank: "1", name: "Kandekar Vedika Gorakshanath", marks: "-", percentage: "88.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "SY", rank: "2", name: "Urane Ankita Laxmikant", marks: "-", percentage: "80.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "SY", rank: "3", name: "Kapale Saurabh Gangadhar", marks: "-", percentage: "79.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "FY", rank: "1", name: "Shelke Kalyani Rajendra", marks: "9.34 (CGPA)", percentage: "-", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "FY", rank: "2", name: "Sekakar Rutuja Dhynaeshwar", marks: "9.3 (CGPA)", percentage: "-", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2020", class: "FY", rank: "3", name: "Nimbalkar Pranali Gangadhar", marks: "9.23 (CGPA)", percentage: "-", program: "F.Y. B.Sc. (Comp. Sci.)" },

  // 2020-21 (Year 2021)
  { year: "2021", class: "FY", rank: "1", name: "Dhawale Ajinkya Balasaheb", marks: "1090/1200", percentage: "90.83%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "FY", rank: "2", name: "Barde Pratik Dilip", marks: "1078/1200", percentage: "89.83%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "FY", rank: "3", name: "Pawar Aishwarya Jaydeep", marks: "1039/1200", percentage: "86.58%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "SY", rank: "1", name: "Shelke Kalyani R", marks: "9.55", percentage: "88.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "SY", rank: "1", name: "Munot Riya Rajendra", marks: "9.55", percentage: "88.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "SY", rank: "2", name: "Mhaske Harshada Satish", marks: "9.45", percentage: "87.00%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "SY", rank: "3", name: "Adhav Vrushali A", marks: "9.18", percentage: "84.3%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "TY", rank: "1", name: "Kandekar Vedika Gorakshanath", marks: "1925/2200", percentage: "87.50%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "TY", rank: "2", name: "Bodkhe Sayali Anil", marks: "1922/2200", percentage: "87.36%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "TY", rank: "3", name: "Wakhare Om Ravindra", marks: "1910/2200", percentage: "86.86%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2021", class: "M.Sc. I", rank: "1", name: "Berad Snehal Satish", marks: "935/1100", percentage: "85.00%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2021", class: "M.Sc. I", rank: "2", name: "Date Suchita Ramdas", marks: "903/1100", percentage: "82.09%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2021", class: "M.Sc. I", rank: "3", name: "Berad Rutuja Ashok", marks: "895/1100", percentage: "81.36%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2021", class: "M.Sc. II", rank: "1", name: "Supekar Sarang Sunil", marks: "1761/2000", percentage: "88.09%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2021", class: "M.Sc. II", rank: "2", name: "Zaware Chaitali Popat", marks: "1674/2000", percentage: "83.70%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2021", class: "M.Sc. II", rank: "3", name: "Akolkar Rushikesh Babasaheb", marks: "1615/2000", percentage: "80.75%", program: "M.Sc. (Comp. Sci.) – II" },

  // 2021-22 (Year 2022)
  { year: "2022", class: "FY", rank: "1", name: "Kute Nikhil Pruthviraj", marks: "9.83", percentage: "93.30%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "FY", rank: "2", name: "Thore Vaishnavi Vijay", marks: "9.73", percentage: "92.30%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "FY", rank: "3", name: "Tokekar Himanshu Sudhir", marks: "9.62", percentage: "91.20%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "FY", rank: "3", name: "Pawar Sakshi Bapurao", marks: "9.62", percentage: "91.20%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "SY", rank: "1", name: "Dhawale Ajinkya Balasaheb", marks: "9.73", percentage: "89.5%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "SY", rank: "2", name: "Kolge Dipali Rajendra", marks: "9.38", percentage: "86.5%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "SY", rank: "2", name: "Lokhande Ashwini Adinath", marks: "9.30", percentage: "85.5%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "SY", rank: "3", name: "Kolhe Prathamesh Vijay", marks: "9.21", percentage: "84.5%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "TY", rank: "1", name: "Shelke Kalyani Rajendra", marks: "9.60", percentage: "91.20%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "TY", rank: "2", name: "Mhaske Harshada Satish", marks: "9.41", percentage: "89.39%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "TY", rank: "3", name: "Pawar Sakshi Dattatraya", marks: "9.13", percentage: "86.74%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2022", class: "M.Sc. I", rank: "1", name: "Misal Aboli Suresh", marks: "8.32", percentage: "79.04%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2022", class: "M.Sc. I", rank: "2", name: "Pandarkar Abhijeet Anil", marks: "8.22", percentage: "78.09%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2022", class: "M.Sc. I", rank: "3", name: "Zarekar Nikita Vishnu", marks: "8.13", percentage: "77.23%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2022", class: "M.Sc. II", rank: "1", name: "Berad Snehal Satish", marks: "9.16", percentage: "85.05%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2022", class: "M.Sc. II", rank: "2", name: "Shete Aditi Dnyaneshwar", marks: "8.75", percentage: "80.73%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2022", class: "M.Sc. II", rank: "3", name: "Yeole Prachi Ramesh", marks: "8.75", percentage: "80.27%", program: "M.Sc. (Comp. Sci.) – II" },

  // 2022-23 (Year 2023)
  { year: "2023", class: "FY", rank: "1", name: "Shelke Sayali Sheshmal", marks: "9.29", percentage: "88.25%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "FY", rank: "2", name: "Shelke Tejaswini Ajinath", marks: "9.09", percentage: "86.36%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "FY", rank: "3", name: "Darekar Jui Abhijeet", marks: "9.00", percentage: "85.50%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "FY", rank: "3", name: "Shelke Akshada Dhondiba", marks: "9.00", percentage: "85.50%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "SY", rank: "1", name: "Sonawane Suraj Kailas", marks: "2231", percentage: "89.24%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "SY", rank: "2", name: "Andhare Supriya Sunil", marks: "2172", percentage: "86.88%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "SY", rank: "2", name: "Bawadkar Madhavi Keshav", marks: "2089", percentage: "83.56%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "TY", rank: "1", name: "Dhawale Ajinkya Balasaheb", marks: "9.76", percentage: "91.33%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "TY", rank: "2", name: "Barde Pratik Dilip", marks: "9.43", percentage: "88.14%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "TY", rank: "3", name: "Kolge Dipali Rajendra", marks: "9.27", percentage: "85.17%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2023", class: "M.Sc. I", rank: "1", name: "Shinde Shivani Jagannath", marks: "1067", percentage: "88.91%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2023", class: "M.Sc. I", rank: "2", name: "Pawar Tanya Kanifnath", marks: "1051", percentage: "87.58%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2023", class: "M.Sc. I", rank: "3", name: "Joshi Sakshi Vijay", marks: "999", percentage: "83.25%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2023", class: "M.Sc. II", rank: "1", name: "Rankhanb Gauri Pravinchand", marks: "1712", percentage: "77.82%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2023", class: "M.Sc. II", rank: "2", name: "Karale Avdhut Ghanshyam", marks: "1697", percentage: "77.14%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2023", class: "M.Sc. II", rank: "3", name: "Kakade Akshada Bharat", marks: "1695", percentage: "77.05%", program: "M.Sc. (Comp. Sci.) – II" },

  // 2023-24 (Year 2024)
  { year: "2024", class: "FY", rank: "1", name: "Kulkarni Sanika Yogesh", marks: "934", percentage: "84.91%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "FY", rank: "2", name: "Jare Archana Bapu", marks: "924", percentage: "84.00%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "FY", rank: "3", name: "Honde Rutuja Dnyaneshwar", marks: "919", percentage: "83.55%", program: "F.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "SY", rank: "1", name: "Shelke Sayali Sheshmal", marks: "9.04", percentage: "85.92%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "SY", rank: "2", name: "Shelke Akshada Dhondiba", marks: "8.95", percentage: "84.98%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "SY", rank: "2", name: "Shelke Tejaswini Ajinath", marks: "8.86", percentage: "84.16%", program: "S.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "TY", rank: "1", name: "Thore Vaishnavi Vijay", marks: "3195/9.43", percentage: "88.75%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "TY", rank: "2", name: "Kule Nikhil Pruthviraj", marks: "3180/9.45", percentage: "88.33%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "TY", rank: "3", name: "Tokekar Himanshu Sudhir", marks: "3170/9.49", percentage: "88.06%", program: "T.Y. B.Sc. (Comp. Sci.)" },
  { year: "2024", class: "M.Sc. I", rank: "1", name: "Wagh Shivani Balasaheb", marks: "981", percentage: "81.75%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2024", class: "M.Sc. I", rank: "2", name: "Aher Abhishek Shivaji", marks: "936", percentage: "78.00%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2024", class: "M.Sc. I", rank: "3", name: "Walke Vaishnavi Dattatraya", marks: "923", percentage: "76.92%", program: "M.Sc. (Comp. Sci.) – I" },
  { year: "2024", class: "M.Sc. II", rank: "1", name: "Pawar Tanaya K", marks: "2054", percentage: "87.40%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2024", class: "M.Sc. II", rank: "2", name: "Shinde Shivani K", marks: "2043", percentage: "86.94%", program: "M.Sc. (Comp. Sci.) – II" },
  { year: "2024", class: "M.Sc. II", rank: "3", name: "Joshi Sakshi Vijay", marks: "2023", percentage: "86.09%", program: "M.Sc. (Comp. Sci.) – II" }
];

console.log(JSON.stringify(toppersRaw.map((t, idx) => ({ id: 500 + idx, ...t })), null, 2));
